/*
 * Swagger HLAHapV
 * This is a HLAHapV Server.  You can find  out more about HLAHapV at  [http://github.com/nmdp-bioinformatics/ImmunogeneticDataTools](http://github.com/nmdp-bioinformatics/ImmunogeneticDataTools). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mpresteg@nmdp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Genotype
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-06T02:02:16.599Z")
public class Genotype {
  @SerializedName("id")
  private String id = null;

  @SerializedName("glString")
  private String glString = null;

  public Genotype id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Genotype glString(String glString) {
    this.glString = glString;
    return this;
  }

   /**
   * Get glString
   * @return glString
  **/
  @ApiModelProperty(required = true, value = "")
  public String getGlString() {
    return glString;
  }

  public void setGlString(String glString) {
    this.glString = glString;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Genotype genotype = (Genotype) o;
    return Objects.equals(this.id, genotype.id) &&
        Objects.equals(this.glString, genotype.glString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, glString);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Genotype {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    glString: ").append(toIndentedString(glString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

