/*
 * Swagger HLAHapV
 * This is a HLAHapV Server.  You can find  out more about HLAHapV at  [http://github.com/nmdp-bioinformatics/ImmunogeneticDataTools](http://github.com/nmdp-bioinformatics/ImmunogeneticDataTools). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mpresteg@nmdp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Genotype;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Genotypes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-06T02:02:16.599Z")
public class Genotypes {
  @SerializedName("genotype")
  private List<Genotype> genotype = new ArrayList<Genotype>();

  public Genotypes genotype(List<Genotype> genotype) {
    this.genotype = genotype;
    return this;
  }

  public Genotypes addGenotypeItem(Genotype genotypeItem) {
    this.genotype.add(genotypeItem);
    return this;
  }

   /**
   * Get genotype
   * @return genotype
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Genotype> getGenotype() {
    return genotype;
  }

  public void setGenotype(List<Genotype> genotype) {
    this.genotype = genotype;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Genotypes genotypes = (Genotypes) o;
    return Objects.equals(this.genotype, genotypes.genotype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genotype);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Genotypes {\n");
    
    sb.append("    genotype: ").append(toIndentedString(genotype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

