/*

    Copyright (c) 2014-2015 National Marrow Donor Program (NMDP)

    This library is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as published
    by the Free Software Foundation; either version 3 of the License, or (at
    your option) any later version.

    This library is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; with out even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
    License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this library;  if not, write to the Free Software Foundation,
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

    > http://www.gnu.org/licenses/lgpl.html

*/
package org.dash;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import org.dash.valid.LinkageDisequilibriumAnalyzer;
import org.dash.valid.LinkagesLoader;
import org.dash.valid.Sample;
import org.dash.valid.freq.Frequencies;
import org.dash.valid.freq.HLAFrequenciesLoader;
import org.dash.valid.gl.GLStringUtilities;
import org.dash.valid.gl.LinkageDisequilibriumGenotypeList;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// syntheticExamples.txt is repo-resident test data (unlike the real-world
// stanfordExamplesFixed.txt file used throughout the 2026-08 modernization/non-determinism
// investigation, which stays outside the repo, on the reporting user's own machine). It's
// generated by SyntheticGLStringGenerator (ld-tools) directly from public NMDP haplotype
// frequency reference data -- population-level statistics, not any individual's genotype
// -- so it represents no real person, and gives this project its first standing,
// repo-resident, full-batch-scale regression check: everything before this was manual,
// ad hoc, against a file that isn't part of the repo at all. See the generator's javadoc
// for exactly how the file's three deliberate scenarios (plain ambiguity, an oversized
// ambiguity that must be rejected, and a genotype-ambiguity G-group tie -- the same
// mechanism investigated and fixed in #122/#125) are constructed.
public class SyntheticExamplesTest {

	// LinkagesLoader/HLAFrequenciesLoader are process-wide singletons whose getInstance()
	// is a no-op once already initialized -- other test classes in this same forked JVM
	// (run in whatever order Surefire picks) can leave them configured for a different
	// Frequencies/Linkages combination than this file's alleles were generated against.
	// Confirmed this test is genuinely order-dependent without this: it passes run in
	// isolation but failed as part of the full suite before this reset was added. Same
	// approach used in LinkageDisequilibriumAnalyzerTest/LinkageDisequilibriumGenotypeListTest.
	@BeforeEach
	public void resetSingletons() throws ReflectiveOperationException {
		resetSingleton(LinkagesLoader.class);
		resetSingleton(HLAFrequenciesLoader.class);
		System.setProperty(Frequencies.FREQUENCIES_PROPERTY, Frequencies.NMDP_2007_STD.getShortName());
	}

	private static void resetSingleton(Class<?> clazz) throws ReflectiveOperationException {
		Field instanceField = clazz.getDeclaredField("instance");
		instanceField.setAccessible(true);
		instanceField.set(null, null);
	}

	@Test
	public void testSyntheticExamplesFileLoads() {
		List<LinkageDisequilibriumGenotypeList> glStrings = GLStringUtilities.readGLStringFile("syntheticExamples.txt");

		assertFalse(glStrings.isEmpty(), "Expected at least one GL string to load from syntheticExamples.txt");
		// The file has 40 lines; at least one is deliberately built to exceed the allele
		// ambiguity threshold and should be silently skipped (per-line, not batch-aborting)
		// rather than loaded -- fewer than 40 loaded confirms that rejection path actually
		// fired against this file, not just the hand-crafted unit test fixture.
		assertTrue(glStrings.size() < 40,
				"Expected at least one deliberately-oversized sample to be rejected by the ambiguity threshold");
	}

	@Test
	public void testSyntheticExamplesProduceRealFindings() throws IOException {
		List<LinkageDisequilibriumGenotypeList> glStrings = GLStringUtilities.readGLStringFile("syntheticExamples.txt");

		List<Sample> samples = new ArrayList<Sample>();
		for (LinkageDisequilibriumGenotypeList glString : glStrings) {
			// Every sample in this file uses only "^"/"+"/"/"/"|" -- never "~" phasing --
			// so this always takes the same code path LinkageDisequilibriumAnalyzer's own
			// batch loop takes for these samples (buildHaplotypes() only returns non-empty
			// for "~"-phased genotypes).
			samples.add(LinkageDisequilibriumAnalyzer.detectLinkages(glString));
		}

		assertEquals(glStrings.size(), samples.size());

		long samplesWithFindings = samples.stream()
				.filter(sample -> sample.getFindings() != null
						&& sample.getFindings().getLinkedPairs() != null
						&& !sample.getFindings().getLinkedPairs().isEmpty())
				.count();

		// Proves the file's core premise -- alleles drawn from real frequency reference
		// data are actually "findable" against this codebase's own reference tables, not
		// just structurally plausible-looking. If this ever drops to 0, the generator or
		// its reference data source has drifted from what this codebase's bundled
		// frequency tables can actually match.
		assertTrue(samplesWithFindings > 0,
				"Expected at least one synthetic sample to produce real linkage findings");
	}
}
