/*
 * Swagger HLAHapV
 * This is a HLAHapV Server.  You can find  out more about HLAHapV at  [http://github.com/nmdp-bioinformatics/ImmunogeneticDataTools](http://github.com/nmdp-bioinformatics/ImmunogeneticDataTools). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mpresteg@nmdp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Genotypes;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenotypesApi
 */
@Ignore
public class GenotypesApiTest {

    private final GenotypesApi api = new GenotypesApi();

    
    /**
     * Submit a set of genotypes for evaluation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitGenotypesTest() throws ApiException {
        Genotypes body = null;
        api.submitGenotypes(body);

        // TODO: test validations
    }
    
}
